workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == 'dev'
    - if: $CI_COMMIT_REF_NAME == 'beta'
variables:
  APP_NAME: 'asset-management'
  USER: 'uhome'
  HOST: '192.168.1.38'
  PASSWORD: 'WvR2inESH97tH^'
  ASSETS_PATH: '/data/segingx/web/'
default:
  image: node:14.10.0
  tags: 
    - docker-did-runner

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:
  stage: build
  cache: 
    paths: 
      - node_modules
  script:
    - npm config set registry https://registry.npmmirror.com
    - npm install --force
    - npm run build
  artifacts:
    name: $APP_NAME
    paths:
      - $APP_NAME

deploy-dev:
  stage: deploy
  image: ictu/sshpass
  rules:
    - if: $CI_COMMIT_REF_NAME == 'dev'
  script:
    - apk add --no-cache tar
    - tar -czvf $APP_NAME.tar.gz $APP_NAME
    - sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no $APP_NAME.tar.gz $USER@$HOST:$ASSETS_PATH
    - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER@$HOST rm -rf $ASSETS_PATH$APP_NAME
    - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER@$HOST tar -zxvf $ASSETS_PATH$APP_NAME.tar.gz -C $ASSETS_PATH
  environment: dev